// error handling

const x = 5;

try {
  x = 7;
  console.log(x);
} catch (error) {
  console.log(error.message);
}

console.log("HI");

console.log(5 * 5);

// try catch

// try => we should put error prone code in try
